# Generated by Django 3.2.3 on 2021-08-21 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата')),
                ('incoming', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Приход')),
                ('expense', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Расход')),
                ('balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='Баланс')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['-create_date'],
            },
        ),
    ]
