# Generated by Django 3.2 on 2021-05-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('incoming', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Приход')),
                ('expense', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Расход')),
                ('balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='Баланс')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('payment', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Оплата')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Коментарий')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Оплата клиента',
                'verbose_name_plural': 'Оплата клиентов',
                'db_table': 'client_pay',
                'ordering': ['create_date'],
            },
        ),
    ]
