# Generated by Django 3.2 on 2021-05-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientPayment',
        ),
    ]
