# Generated by Django 3.2 on 2021-04-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashboxName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('monthly_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.address')),
            ],
        ),
        migrations.CreateModel(
            name='KindOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_activity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ter_numb', models.CharField(blank=True, max_length=50, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='kind_of_activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.kindofactivity'),
        ),
        migrations.CreateModel(
            name='Cashboxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ident_numb', models.CharField(blank=True, max_length=50, null=True)),
                ('cashb_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.cashboxname')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.client')),
                ('iep_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_2.indentr')),
            ],
        ),
    ]
