# Generated by Django 3.2 on 2021-05-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address',
                'ordering': ['city', 'street'],
            },
        ),
        migrations.CreateModel(
            name='CashbName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashb_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель кассы')),
            ],
            options={
                'verbose_name': 'Кассы (модели)',
                'verbose_name_plural': 'Кассы (модели)',
                'db_table': 'cashb_names',
                'ordering': ['cashb_name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('tel_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Тел.')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата заключения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
                'db_table': 'contract',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='IndEntr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ф.И.О')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес регистрации')),
                ('ident_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('tel_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Тел.')),
                ('channel', models.CharField(blank=True, max_length=2, null=True, verbose_name='Канал')),
                ('el_key', models.BooleanField(default=True, verbose_name='Электронный ключ')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('type_of_activity', models.CharField(blank=True, choices=[('SOLDAT', 'Soldat'), ('CHISTIY', 'Chistiy')], max_length=50, null=True, verbose_name='Тип')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль от почты')),
                ('reg_date', models.DateField(verbose_name='Дата регистрации')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Индивидуальный Предпрениматель',
                'verbose_name_plural': 'Индивидуальные Предпрениматели',
                'db_table': 'ind_entr',
                'ordering': ['type_of_activity'],
            },
        ),
        migrations.CreateModel(
            name='KindOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kofa', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Клиент (вид деятельности клиента)',
                'verbose_name_plural': 'Клиенты (виды деятельности клиентов)',
                'db_table': 'kind_of_activity',
                'ordering': ['kofa'],
            },
        ),
        migrations.CreateModel(
            name='Terminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_numb', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер терминала')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
                'db_table': 'terminals',
                'ordering': ['term_numb'],
            },
        ),
        migrations.CreateModel(
            name='IndEntrInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('login', models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль')),
                ('bank', models.CharField(blank=True, choices=[('Sberbank', 'Sberbank'), ('Tinkoff', 'Tinkoff'), ('Tochka', 'Tochka')], max_length=50, null=True, verbose_name='Банк')),
                ('card', models.CharField(blank=True, max_length=50, null=True, verbose_name='Карта')),
                ('codeword', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кодовое слово')),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.indentr', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'Инфо. Индивидуального Предпренимателя',
                'verbose_name_plural': 'Инфо. Индивидуальных Предпренимателей',
                'db_table': 'ind_entr_info',
                'ordering': ['bank'],
            },
        ),
        migrations.CreateModel(
            name='Cashboxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(verbose_name='Дата регистрации')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('ident_numb', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер кассы')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.address', verbose_name='Адрес')),
                ('cashb_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.cashbname', verbose_name='Модель кассы')),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.indentr', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'db_table': 'cashboxes',
                'ordering': ['cashb_name'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='address',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='address',
            name='kofa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.kindofactivity', verbose_name='Вид деятельности'),
        ),
    ]
