# Generated by Django 3.2.3 on 2021-06-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminals',
            name='address',
        ),
        migrations.AlterField(
            model_name='cashboxes',
            name='cashb_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.cashbname', verbose_name='Модель кассы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.cashboxes', verbose_name='Касса'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.clientinfo', verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kofa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.kindofactivity', verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='indentrinfo',
            name='iep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.indentr', verbose_name='ИП'),
        ),
    ]
