# Generated by Django 3.2.3 on 2021-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20210617_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оплата клиента'),
        ),
    ]
