# Generated by Django 3.2.3 on 2021-05-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20210518_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Тел.'),
        ),
    ]
