# Generated by Django 3.2.3 on 2021-05-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_client_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbname',
            name='cashb_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Модель кассы'),
        ),
    ]
