# Generated by Django 3.2.3 on 2021-07-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_client_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashboxes',
            name='cashb_name',
        ),
        migrations.RemoveField(
            model_name='cashboxes',
            name='iep',
        ),
        migrations.DeleteModel(
            name='Terminals',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cashbox',
        ),
        migrations.AddField(
            model_name='client',
            name='cashbox_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель кассы'),
        ),
        migrations.AddField(
            model_name='client',
            name='cashbox_numb',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер кассы'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='client',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='client',
            name='iep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.indentr', verbose_name='ИП Кассы'),
        ),
        migrations.AddField(
            model_name='client',
            name='reg_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='client',
            name='term_numb',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер терминала'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kofa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оплата'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='CashbName',
        ),
        migrations.DeleteModel(
            name='Cashboxes',
        ),
        migrations.DeleteModel(
            name='KindOfActivity',
        ),
    ]
