# Generated by Django 3.2.3 on 2021-05-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_cashbname_cashb_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.address', verbose_name='Адрес'),
        ),
    ]
