# Generated by Django 3.2.3 on 2021-07-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_auto_20210730_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract',
        ),
        migrations.AddField(
            model_name='client',
            name='contract_create_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения договора'),
        ),
        migrations.AddField(
            model_name='client',
            name='contract_desc',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Коментарий к договору'),
        ),
        migrations.AddField(
            model_name='client',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания договора'),
        ),
    ]
