# Generated by Django 3.2.3 on 2021-08-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_auto_20210730_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
