# Generated by Django 3.2.3 on 2021-08-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_delete_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='улица'),
        ),
    ]
