# Generated by Django 3.2.3 on 2021-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_alter_client_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contract_create_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закл. договора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заверш. договора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата кон. кассы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reg_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рег. кассы'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
